# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Elizabeth Barna
email: elizabeth.k.barna@vanderbilt.edu
description: >- In a time when more American museums strive to acknowledge neglected histories of chattel slavery and indigenous genocide, what factors influence the ways they present these histories to the public?  When many visitors expect nostalgic renditions of that past, how are we to educate for the future?  As a sociologist and public historian, I address these questions in my dissertation, tentatively entitled, “Andrew Jackson for the 21st Century: Hermitage between Slavery and the Trail of Tears in an Age of Right-Wing Populism."  Based on nearly a year of participant-observation as a historic interpreter at Andrew Jackson’s Hermitage, I identify factors influencing representations of slavery, genocide, and democracy at this presidential house museum and plantation site.  My research sits at the intersection of Social Memory Studies; Organizations, Occupations, and Work; Culture; and Race and Racism, and has implications for museum education in an age of intense polarization. I have presented on my work internationally and am currently writing a minibook under contract with Vanderbilt University Press, entitled Man of His Time?  Teaching about Andrew Jackson in the Age of Trump. I am a Mellon Graduate Fellow in Digital Humanities at Vanderbilt’s Center for Digital Humanities, where I am partnering with the Historic Franklin Masonic Hall to create an ArcGIS StoryMap highlighting Black and indigenous history in downtown Franklin.  I am also a HASTAC Scholar in partnership with the Center for Digital Humanities and the Department of American Studies at Vanderbilt, where I am co-organizing a tour on local Native American history tentatively entitled, “Ecologies of Memory and Erasure.” I am currently the Book Review Editor for Work and Occupations, and, like my dissertation, my Master’s thesis and undergraduate capstone were organizational ethnographies.  I received my B.A. in Sociology and B.S. in Environmental Science from California Lutheran University in 2013, and my M.A. in Sociology from Vanderbilt University in 2016.



baseurl: "/elizabethbarna" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "Elizabe60545369"
github_username:  ElizabethBarna

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
